"""Add author model and status field to book

Revision ID: 4c5544ef038d
Revises: 60461bf618a4
Create Date: 2024-06-18 12:48:26.547685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5544ef038d'
down_revision = '60461bf618a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('status', sa.String(length=10), nullable=False))
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_book_author', table_name='book')
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    op.drop_column('book', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_index('ix_book_author', 'book', ['author'], unique=False)
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('book', 'status')
    op.drop_column('book', 'author_id')
    op.drop_table('author')
    # ### end Alembic commands ###
